POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlZ2lzdGVydXNlcjFAZXhhbXBsZS5jb20iLCJleHAiOjE3MjAzNzUzNzMsInVzZXJJZCI6MX0.D164k3lg06n5lEUGwSJokxeZSfzW4EsxSxo5y8HWMsE
    
    {
  
    "name": "test event name",
    "description": "d",
    "location": "d",
    "dateTime": "d"
   
}
